app:
  address: ":8080"
  shutdown_timeout: 20s
  secret_key: 012345678901234567890123456789123456
  token_duration: 1h

db:
  host: restaurant_db
  port: 5432
  username: admin
  password: secret
  name: restaurant_reservation