openapi: 3.0.0
info:
  title: Restaurant Reservation API
  version: 0.0.1

paths:
  /users:
    post:
      tags:
        - users
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  format: string
                  example: user1
                password:
                  type: string
                  format: password
                  example: 12345678
      responses:
        400:
          description: bad request
        201:
          description: user created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 1
                  username:
                    type: string
                    format: string
                    example: user1
  
  /users/login:
    post:
      tags:
        - users
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  format: string
                  example: user1
                password:
                  type: string
                  format: password
                  example: 12345678
      responses:
        400:
          description: bad request
        404:
          description: username or password is wrong
        200:
          description: user logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    format: string
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: int64
                        example: 1
                      username:
                        type: string
                        format: string
                        example: user1

  /book:
    post:
      tags:
        - booking
      summary: Book a table
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                seats_count:
                  type: integer
                  format: int64
                  example: 3
                date:
                  type: string
                  format: date
                  example: 2025-01-01
      responses:
        400:
          description: bad request
        404:
          description: no table is available
        201:
          description: table booked
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 1
                  table_id:
                    type: integer
                    format: int64
                    example: 1
                  seats_count:
                    type: integer
                    format: int64
                    example: 4
                  price:
                    type: integer
                    format: int64
                    example: 400

  /cancel:
    post:
      tags:
        - booking
      summary: Cancel a reservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                  example: 1
      responses:
        400:
          description: bad request
        404:
          description: table not found
        200:
          description: table canceled